dependencies:
  pre:
    - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome.deb
    - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
    - rm google-chrome.deb
machine: # 虛擬機的環境
  java:
    version: openjdk8
  node:
    version: 7.10.0
jobs:
  build:
    # docker:
    #   - image: buildpack-deps:trusty
    # environment:
    #   - FOO: "bar"
    # parallelism: 3
    # resource_class: large
    # working_directory: ~/my-app
    # branches:
    #   only:
    #     - master
    #     - /rc-.*/
    steps:
      - run: npm run build

